export type Location =  {
  itstId: string,
  itstNm: string,
  mapCtptIntLat: number,
  mapCtptIntLot: number,
  laneWidth?: number,
  limitSpedTypeNm?: string,
  limitSped?: string,
  itstEngNm?: string,
  rgtrId: string,
  regDt: Date,
}

export type UpdatedLocation = Location & {lat: number, lng: number};

export type SignalInformation = UpdatedLocation & {phase: string, timing: number};

export type SignalTiming = {
  dataId: string;
  trsmDy: number;
  trsmUtcTime: number;
  trsmYear: string;
  trsmMt: string;
  trsmTm: string;
  trsmMs: string;
  itstId: string;
  eqmnId: string;
  msgCreatMin: number;
  msgCreatDs: number;
  ntBssgRmdrCs?: number;
  ntBcsgRmdrCs?: number;
  ntLtsgRmdrCs?: number;
  ntPdsgRmdrCs?: number;
  ntStsgRmdrCs?: number;
  ntUtsgRmdrCs?: number;
  etBssgRmdrCs?: number;
  etBcsgRmdrCs?: number;
  etLtsgRmdrCs?: number;
  etPdsgRmdrCs?: number;
  etStsgRmdrCs?: number;
  etUtsgRmdrCs?: number;
  stBssgRmdrCs?: number;
  stBcsgRmdrCs?: number;
  stLtsgRmdrCs?: number;
  stPdsgRmdrCs?: number;
  stStsgRmdrCs?: number;
  stUtsgRmdrCs?: number;
  wtBssgRmdrCs?: number;
  wtBcsgRmdrCs?: number;
  wtLtsgRmdrCs?: number;
  wtPdsgRmdrCs?: number;
  wtStsgRmdrCs?: number;
  wtUtsgRmdrCs?: number;
  neBssgRmdrCs?: number;
  neBcsgRmdrCs?: number;
  neLtsgRmdrCs?: number;
  nePdsgRmdrCs?: number;
  neStsgRmdrCs?: number;
  neUtsgRmdrCs?: number;
  seBssgRmdrCs?: number;
  seBcsgRmdrCs?: number;
  seLtsgRmdrCs?: number;
  sePdsgRmdrCs?: number;
  seStsgRmdrCs?: number;
  seUtsgRmdrCs?: number;
  swBssgRmdrCs?: number;
  swBcsgRmdrCs?: number;
  swLtsgRmdrCs?: number;
  swPdsgRmdrCs?: number;
  swStsgRmdrCs?: number;
  swUtsgRmdrCs?: number;
  nwBssgRmdrCs?: number;
  nwBcsgRmdrCs?: number;
  nwLtsgRmdrCs?: number;
  nwPdsgRmdrCs?: number;
  nwStsgRmdrCs?: number;
  nwUtsgRmdrCs?: number;
  rgtrId: string;
  regDt: Date;
}

export type SignalPhase = {
  dataId: string;
  trsmDy: number;
  trsmUtcTime: number;
  trsmYear: string;
  trsmMt: string;
  trsmTm: string;
  trsmMs: string;
  itstId: string;
  eqmnId: string;
  ntStsgStatNm?: string;
  ntBssgStatNm?: string;
  ntBcsgStatNm?: string;
  ntLtsgStatNm?: string;
  ntPdsgStatNm?: string;
  ntUtsgStatNm?: string;
  etBssgStatNm?: string;
  etBcsgStatNm?: string;
  etLtsgStatNm?: string;
  etPdsgStatNm?: string;
  etStsgStatNm?: string;
  etUtsgStatNm?: string;
  stBssgStatNm?: string;
  stBcsgStatNm?: string;
  stLtsgStatNm?: string;
  stPdsgStatNm?: string;
  stStsgStatNm?: string;
  stUtsgStatNm?: string;
  wtBssgStatNm?: string;
  wtBcsgStatNm?: string;
  wtLtsgStatNm?: string;
  wtPdsgStatNm?: string;
  wtStsgStatNm?: string;
  wtUtsgStatNm?: string;
  neBssgStatNm?: string;
  neBcsgStatNm?: string;
  neLtsgStatNm?: string;
  nePdsgStatNm?: string;
  neStsgStatNm?: string;
  neUtsgStatNm?: string;
  seBssgStatNm?: string;
  seBcsgStatNm?: string;
  seLtsgStatNm?: string;
  sePdsgStatNm?: string;
  seStsgStatNm?: string;
  seUtsgStatNm?: string;
  swBssgStatNm?: string;
  swBcsgStatNm?: string;
  swLtsgStatNm?: string;
  swPdsgStatNm?: string;
  swStsgStatNm?: string;
  swUtsgStatNm?: string;
  nwBssgStatNm?: string;
  nwBcsgStatNm?: string;
  nwLtsgStatNm?: string;
  nwPdsgStatNm?: string;
  nwStsgStatNm?: string;
  nwUtsgStatNm?: string;
  rgtrId: string;
  regDt: Date;
};
