import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useRecoilState, useSetRecoilState } from 'recoil';
import SignalList from '../Components/SignalList';
import myPositionState from '../recoil/myPosition/atom';
import { aroundSignalsAtom } from '../recoil/aroundSignals/atom';
import filterSignals from '../utils/filterSignals';
import mapPositionAtom from '../recoil/mapPosition/atom';
import getDistance from '../utils/getDistance';
import mapMovingAtom from '../recoil/mapMoving/atom';
import getSignalData from '../utils/getSignalData';
import placeSignal from '../utils/placeSignal';

const Home: NextPage = () => {
  const [myPosition, setMyPosition] = useRecoilState(myPositionState);
  const [mapPosition, setMapPosition] = useRecoilState(mapPositionAtom);
  const [isMapMoving, setIsMapMoving] = useRecoilState(mapMovingAtom);
  const setAroundSignals = useSetRecoilState(aroundSignalsAtom);
  const [mapLoaded, setMapLoaded] = useState<boolean>(false);
  const [map, setMap] = useState();

  useEffect(() => {
    getDistance(myPosition, mapPosition) > 0.5 ?
    setIsMapMoving(true) :
    setIsMapMoving(false);
  }, [mapPosition]);

  useEffect(() => {
    if (!isMapMoving) return;

    (async() => {
      const response = await getSignalData(mapPosition);

      if (!response.length) return;

      const filteredSignals = filterSignals(response);

      filteredSignals.forEach((position: any) => {
        Object.keys(position.phase).forEach(direction => {
          placeSignal(position, direction, position.phase[direction], map);
        });
      });
    })();
  }, [isMapMoving, mapPosition]);

  useEffect(() => {
    (async() => {
      const response = await getSignalData(myPosition);

      if (!response.length) return;
  
      const filteredSignals = filterSignals(response);
  
      setAroundSignals(filteredSignals as any);
    })();
  }, [myPosition]);

  useEffect(() => {
    if (!mapLoaded) return;

    new window.kakao.maps.load(() => {
      const container = document.querySelector("#map");
      const options = {
        center: new window.kakao.maps.LatLng(myPosition.lat, myPosition.lng),
			  level: 2
      };
      const map = new window.kakao.maps.Map(container, options);

      map.panTo(new window.kakao.maps.LatLng(myPosition.lat, myPosition.lng));

      const gpsContent = `<div id="me"></div>`;
      const currentOverlay = new window.kakao.maps.CustomOverlay({
          position: new window.kakao.maps.LatLng(myPosition.lat, myPosition.lng),
          content: gpsContent,
          map: map
      });

      currentOverlay.setMap(map);
      setMap(map);

      new window.kakao.maps.event.addListener(map, "dragend", () => {
        const center = map.getCenter();
        const position = {
          lat: center.getLat(),
          lng: center.getLng(),
        };

        setMapPosition(position);
      });
    });
  }, [mapLoaded, myPosition.lat, myPosition.lng]);

  useEffect(() => {
    navigator.geolocation.getCurrentPosition((pos) => {
      const cord = pos.coords;
      const newPosition = {
        lat: cord.latitude,
        lng: cord.longitude,
      }

      setMyPosition(newPosition);
    }, (err) => {
      console.log(err);
    });
  }, []);

  useEffect(() => {
    const script = document.createElement("script");

    script.src = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAOMAP_API_KEY}&autoload=false`;
    script.addEventListener("load", () => setMapLoaded(true));

    document.head.append(script);
  }, []);

  return (
    <div>
      <Head>
        <title>Walk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="map" style={{ width: "100vw", height: "100vh"}}></div>
      <SignalList map={map} />
    </div>
  )
}

export default Home
